$ANSIBLE_VAULT;1.1;AES256
32623365626637393034313933373939623763646662636334323362646637346433353231306332
3035383065393835653461623039653636613466346337320a666632343237393532313433316137
61326237383264356264646661396532386362663463613464653066366432303030313764396234
3030346533663861660a626666343264633335383961376131666133613833663466653431623131
65356236643261616666386562333834626465363739613061313265623061353434
