---
all:
  children:
    proxmox:
      hosts:
        ms-01:
          ansible_host: 192.168.0.11
        ms-02:
          ansible_host: 192.168.0.12
        ms-03:
          ansible_host: 192.168.0.13
      vars:
        proxmox_cluster_name: technis
        proxmox_ring0_network: 192.168.0.0/24
        proxmox_ring1_network: 192.168.144.0/24
        proxmox_vip: 192.168.0.10
  vars:
    ansible_python_interpreter: /usr/bin/python3
    domain: techn.is
    lan_network: 192.168.0.0/24
