---
kernel_parameters:
  fs.file-max: 2097152
  net.core.rmem_max: 134217728
  net.core.wmem_max: 134217728
  net.ipv4.ip_forward: 1
  net.ipv6.conf.all.forwarding: 1
  vm.dirty_background_ratio: 5
  vm.dirty_ratio: 10
  vm.swappiness: 10
  vm.vfs_cache_pressure: 50
proxmox_packages:
  - btop
  - fio
  - glances
  - iftop
  - iotop
  - lm-sensors
  - ncdu
  - nvme-cli
  - smartmontools
